app = 'llm-code-review-assistant'
primary_region = 'sjc'

[env]
PORT = "8000"

[processes]
app = "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[deploy]
  strategy = "immediate"

# Remove the [[vm]] section entirely - use defaults